FROM cwpearson/latex:science
LABEL maintainer="carl.w.pearson@gmail.com"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy --no-install-recommends --no-install-suggests \
    texlive-latex-extra \
    texlive-pictures \
    pgf \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
