FROM ubuntu:xenial
LABEL maintainer="carl.w.pearson@gmail.com"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy --no-install-recommends \
    graphviz \
    inkscape \
    make \
    python \
    python-pip \
    texlive-base \
    && rm -rf /var/lib/apt/lists/*

RUN pip install seaborn

WORKDIR /data
VOLUME ["/data"]
