FROM cwpearson/latex:heavy
LABEL maintainer="carl.w.pearson@gmail.com"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy --no-install-recommends \
  texlive-full \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
